"""Add files

Revision ID: 03f55440de1a
Revises: 0a7148539259
Create Date: 2026-02-25 21:04:25.626870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f55440de1a'
down_revision: Union[str, Sequence[str], None] = '0a7148539259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='filestatus').create(op.get_bind())
    op.create_table('files',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public file UUID'),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='filestatus'), nullable=False, comment='Статус файла'),
    sa.Column('order_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='filestatus').drop(op.get_bind())
    # ### end Alembic commands ###
