"""Add hashsum

Revision ID: 07dc7a6ddf0c
Revises: 03f55440de1a
Create Date: 2026-02-26 00:02:46.872759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dc7a6ddf0c'
down_revision: Union[str, Sequence[str], None] = '03f55440de1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('hash_sum', sa.String(), nullable=False))
    op.create_index(op.f('ix_files_hash_sum'), 'files', ['hash_sum'], unique=True)
    op.create_unique_constraint(None, 'files', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_index(op.f('ix_files_hash_sum'), table_name='files')
    op.drop_column('files', 'hash_sum')
    # ### end Alembic commands ###
