"""Orders Status

Revision ID: 0a7148539259
Revises: ee4ab8de3b5e
Create Date: 2026-02-23 20:58:43.251501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a7148539259'
down_revision: Union[str, Sequence[str], None] = 'ee4ab8de3b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus').create(op.get_bind())
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'),
                    comment='Статус заказа',
                    existing_nullable=False,
                    postgresql_using='status::text::orderstatus')
    op.create_unique_constraint(None, 'orders', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'status',
                    existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'),
                    type_=sa.VARCHAR(),
                    comment=None,
                    existing_comment='Статус заказа',
                    existing_nullable=False, postgresql_using='status::text')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus').drop(op.get_bind())
    # ### end Alembic commands ###
