"""Add Details, Marks

Revision ID: 66a8ba93d130
Revises: 07dc7a6ddf0c
Create Date: 2026-03-08 12:11:23.703341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a8ba93d130'
down_revision: Union[str, Sequence[str], None] = '07dc7a6ddf0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus').create(op.get_bind())
    op.create_table('marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Айди марки'),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('square', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cooperation', sa.String(), nullable=True),
    sa.Column('kmd_title', sa.String(), nullable=True),
    sa.Column('kmd_num', sa.String(), nullable=True),
    sa.Column('order_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID детали'),
    sa.Column('num_detail', sa.String(), nullable=False),
    sa.Column('gost', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('steel_grade', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('details_quantity', sa.Integer(), nullable=False),
    sa.Column('square', sa.Float(), nullable=False),
    sa.Column('hole_diameter', sa.Float(), nullable=True),
    sa.Column('hole_quantity', sa.Integer(), nullable=True),
    sa.Column('que_num', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus'), nullable=False, comment='Статус детади'),
    sa.Column('mounting_part', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('marks_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marks_id'], ['marks.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_details_num_detail'), 'details', ['num_detail'], unique=False)
    op.create_index(op.f('ix_details_type'), 'details', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_details_type'), table_name='details')
    op.drop_index(op.f('ix_details_num_detail'), table_name='details')
    op.drop_table('details')
    op.drop_table('marks')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus').drop(op.get_bind())
    # ### end Alembic commands ###
