"""Update File

Revision ID: b01731356ccd
Revises: 66a8ba93d130
Create Date: 2026-03-12 12:10:55.267585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01731356ccd'
down_revision: Union[str, Sequence[str], None] = '66a8ba93d130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='filestatus',
        new_values=['NEW', 'IN_PROGRESS', 'COMPLETED', 'ERROR'],
        affected_columns=[TableReference(table_schema='public', table_name='files', column_name='status')],
        enum_values_to_rename=[],
    )
    op.create_unique_constraint(None, 'details', ['id'])
    op.add_column('files', sa.Column('comment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'marks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='unique')
    op.drop_column('files', 'comment')
    op.drop_constraint(None, 'details', type_='unique')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='filestatus',
        new_values=['NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='files', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
