"""Orders

Revision ID: ee4ab8de3b5e
Revises: c9610db685bc
Create Date: 2026-02-18 15:36:57.786889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4ab8de3b5e'
down_revision: Union[str, Sequence[str], None] = 'c9610db685bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public order UUID'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_num_orders', sa.Integer(), nullable=False, comment='Внутренний номер заказа'),
    sa.Column('num_orders', sa.Integer(), nullable=False, comment='Номер заказа'),
    sa.Column('num_project', sa.String(), nullable=False, comment='Номер проекта'),
    sa.Column('internal_create_date', sa.Date(), nullable=False, comment='Дата создания самого заказа не в приложении'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('orders')
    # ### end Alembic commands ###
