services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_bkp
    hostname: redis_bkp
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped
    command: >
      redis-server
      /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
#    networks:
#      - internal_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  postgres:
    image: postgres:16-alpine
    container_name: postgres_bkp
    hostname: postgres_bkp
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
#    networks:
#      - internal_network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

#  nats:
#    image: nats:2.11-alpine
#    ports:
#      - "127.0.0.1:4222:4222"  # только localhost!
#    networks:
#      - internal_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

#networks:
#  internal_network:
#    driver: bridge
#    internal: true