"""update delivery2

Revision ID: 097a4fbacd76
Revises: 68bfeddf6ca1
Create Date: 2026-05-20 12:19:45.526933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097a4fbacd76'
down_revision: Union[str, Sequence[str], None] = '68bfeddf6ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Распределено по КМД, кг',
               existing_comment='Уже распределено, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Уже распределено, кг',
               existing_comment='Распределено по КМД, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###
