"""Update marks

Revision ID: 129111118b47
Revises: 74a9a393dff8
Create Date: 2026-05-18 13:22:51.745586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '129111118b47'
down_revision: Union[str, Sequence[str], None] = '74a9a393dff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'ASSEMBLED', 'SHIPPED', name='markstatus').create(op.get_bind())
    op.add_column('marks', sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'ASSEMBLED', 'SHIPPED', name='markstatus', create_type=False), server_default='NEW', nullable=False, comment='Статус марки'))
    op.add_column('marks', sa.Column('assembled_quantity', sa.Integer(), server_default='0', nullable=False, comment='Количество собранных марок'))
    op.add_column('marks', sa.Column('shipped_quantity', sa.Integer(), server_default='0', nullable=False, comment='Количество отгруженных марок'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'shipped_quantity')
    op.drop_column('marks', 'assembled_quantity')
    op.drop_column('marks', 'status')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'ASSEMBLED', 'SHIPPED', name='markstatus').drop(op.get_bind())
    # ### end Alembic commands ###
