"""new update quantity

Revision ID: 15a2ac6c3c1e
Revises: cca6a2d75195
Create Date: 2026-06-02 07:55:24.893241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a2ac6c3c1e'
down_revision: Union[str, Sequence[str], None] = 'cca6a2d75195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_item', 'total_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Кг, общий вес позиции',
               existing_nullable=False)
    op.alter_column('delivery_item', 'unit_weight',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кг на штуку (корректируется пользователем)',
               existing_nullable=False)
    op.alter_column('delivery_item', 'total_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Штук по документам (справочно)',
               existing_nullable=False)
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Кг, уже распределено в КМД. Синхронизируется через recalculate_allocated_weight()',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment=None,
               existing_comment='Кг, уже распределено в КМД. Синхронизируется через recalculate_allocated_weight()',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('delivery_item', 'total_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment=None,
               existing_comment='Штук по документам (справочно)',
               existing_nullable=False)
    op.alter_column('delivery_item', 'unit_weight',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кг на штуку (корректируется пользователем)',
               existing_nullable=False)
    op.alter_column('delivery_item', 'total_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment=None,
               existing_comment='Кг, общий вес позиции',
               existing_nullable=False)
    # ### end Alembic commands ###
