"""Update uq and kmd

Revision ID: 25971e5c3c24
Revises: e73a314f3d4d
Create Date: 2026-03-27 21:27:08.635512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25971e5c3c24'
down_revision: Union[str, Sequence[str], None] = 'e73a314f3d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kmd', sa.Column('count_marks_uq', sa.Integer(), server_default='0', nullable=False))
    op.add_column('kmd', sa.Column('count_marks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('kmd', sa.Column('marks_weight', sa.Float(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_kmd_num_kmd'), table_name='kmd')
    op.create_index(op.f('ix_kmd_num_kmd'), 'kmd', ['num_kmd'], unique=True)
    op.create_unique_constraint(None, 'orders', ['internal_num_orders'])
    op.create_unique_constraint(None, 'orders', ['num_orders'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_index(op.f('ix_kmd_num_kmd'), table_name='kmd')
    op.create_index(op.f('ix_kmd_num_kmd'), 'kmd', ['num_kmd'], unique=False)
    op.drop_column('kmd', 'marks_weight')
    op.drop_column('kmd', 'count_marks')
    op.drop_column('kmd', 'count_marks_uq')
    # ### end Alembic commands ###
