"""Update order

Revision ID: 2ff3452720c6
Revises: e6de5eddf137
Create Date: 2026-04-22 17:47:31.545636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff3452720c6'
down_revision: Union[str, Sequence[str], None] = 'e6de5eddf137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'num_orders',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='Номер заказа',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'num_orders',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='Номер заказа',
               existing_nullable=False)
    # ### end Alembic commands ###
