"""add delivery

Revision ID: 35359b1cc66d
Revises: 47e5c5a4cfb3
Create Date: 2026-05-20 11:56:10.513448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35359b1cc66d'
down_revision: Union[str, Sequence[str], None] = '47e5c5a4cfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_truck',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название/номер поставки'),
    sa.Column('delivery_date', sa.Date(), nullable=False, comment='Дата прибытия'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='Примечание'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.String(), nullable=False, comment='Тип: Лист, Труба...'),
    sa.Column('profile_size', sa.String(), nullable=False, comment='Типоразмер: 10, 25Ш1...'),
    sa.Column('steel_grade', sa.String(), nullable=False, comment='Марка стали'),
    sa.Column('total_weight', sa.Numeric(precision=15, scale=3), nullable=False, comment='Общий вес в поставке, кг'),
    sa.Column('allocated_weight', sa.Numeric(precision=15, scale=3), server_default='0', nullable=False, comment='Уже распределено, кг'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['delivery_truck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_allocation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('kmd_uuid', sa.UUID(), nullable=False, comment='КМД в который распределяется металл'),
    sa.Column('allocated_weight', sa.Numeric(precision=15, scale=3), nullable=False, comment='Кг из этой позиции в этот КМД'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_item.id'], ),
    sa.ForeignKeyConstraint(['kmd_uuid'], ['kmd.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_item_id', 'kmd_uuid', name='unique_item_kmd')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_allocation')
    op.drop_table('delivery_item')
    op.drop_table('delivery_truck')
    # ### end Alembic commands ###
