"""Delet quantite

Revision ID: 4466ef719e58
Revises: 8c74db3a29b2
Create Date: 2026-03-12 14:10:54.989959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4466ef719e58'
down_revision: Union[str, Sequence[str], None] = '8c74db3a29b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'details', ['id'])
    op.drop_column('details', 'quantity')
    op.create_unique_constraint(None, 'files', ['uuid'])
    op.create_unique_constraint(None, 'kmd', ['uuid'])
    op.create_unique_constraint(None, 'marks', ['id'])
    op.create_unique_constraint(None, 'orders', ['uuid'])
    op.create_unique_constraint(None, 'rel_markadel', ['id'])
    op.create_unique_constraint(None, 'rel_userdel', ['id'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'rel_userdel', type_='unique')
    op.drop_constraint(None, 'rel_markadel', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'marks', type_='unique')
    op.drop_constraint(None, 'kmd', type_='unique')
    op.drop_constraint(None, 'files', type_='unique')
    op.add_column('details', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False, comment='Количество деталей на марку'))
    op.drop_constraint(None, 'details', type_='unique')
    # ### end Alembic commands ###
