"""Update kmd

Revision ID: 47e5c5a4cfb3
Revises: 7e692bc98a0e
Create Date: 2026-05-18 13:43:47.930764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e5c5a4cfb3'
down_revision: Union[str, Sequence[str], None] = '7e692bc98a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kmd', sa.Column('shipped_marks_count', sa.Integer(), server_default='0', nullable=False, comment='Количество отгруженных марок'))
    op.add_column('kmd', sa.Column('shipped_marks_weight', sa.Numeric(precision=20, scale=3), server_default='0', nullable=False, comment='Вес отгруженных марок, кг'))
    op.alter_column('kmd', 'uuid',
               existing_type=sa.UUID(),
               comment='KMD UUID',
               existing_comment='kdm UUID',
               existing_nullable=False)
    op.alter_column('kmd', 'count_marks_uq',
               existing_type=sa.INTEGER(),
               comment='Количество уникальных марок',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('kmd', 'count_marks',
               existing_type=sa.INTEGER(),
               comment='Общее количество марок (с учётом quantity)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('kmd', 'marks_weight',
               existing_type=sa.NUMERIC(precision=20, scale=3),
               comment='Общий вес всех марок, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.create_unique_constraint(None, 'mark_shipment', ['id'])
    op.create_unique_constraint(None, 'rel_user_mark', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rel_user_mark', type_='unique')
    op.drop_constraint(None, 'mark_shipment', type_='unique')
    op.alter_column('kmd', 'marks_weight',
               existing_type=sa.NUMERIC(precision=20, scale=3),
               comment=None,
               existing_comment='Общий вес всех марок, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('kmd', 'count_marks',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Общее количество марок (с учётом quantity)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('kmd', 'count_marks_uq',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество уникальных марок',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('kmd', 'uuid',
               existing_type=sa.UUID(),
               comment='kdm UUID',
               existing_comment='KMD UUID',
               existing_nullable=False)
    op.drop_column('kmd', 'shipped_marks_weight')
    op.drop_column('kmd', 'shipped_marks_count')
    # ### end Alembic commands ###
