"""Update users

Revision ID: 4d34a58cf00c
Revises: dd8f0e39de01
Create Date: 2026-04-08 21:05:39.276838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d34a58cf00c'
down_revision: Union[str, Sequence[str], None] = 'dd8f0e39de01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_login', sa.Boolean(), nullable=False, comment='Can the user login?'))
    op.add_column('users', sa.Column('permissions', sa.VARCHAR(length=10), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Active user',
               existing_comment=' Active user',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Unique email address'))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Verified user or confirmed email'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=' Active user',
               existing_comment='Active user',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'is_login')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
