"""update delivery2

Revision ID: 630e2b20e7ae
Revises: 097a4fbacd76
Create Date: 2026-05-20 22:32:48.742111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630e2b20e7ae'
down_revision: Union[str, Sequence[str], None] = '097a4fbacd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('details', 'operation')
    op.add_column('rel_markadel', sa.Column('operation', sa.String(), nullable=True, comment='Операции наверное могут быт пустыми'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_markadel', 'operation')
    op.add_column('details', sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Операции наверное могут быт пустыми'))
    # ### end Alembic commands ###
