"""Add new tables RelUserMark MarkShipment

Revision ID: 7e692bc98a0e
Revises: 129111118b47
Create Date: 2026-05-18 13:24:15.348559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e692bc98a0e'
down_revision: Union[str, Sequence[str], None] = '129111118b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark_shipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID отгрузки'),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False, comment='Кто оформил отгрузку'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество отгруженных марок'),
    sa.Column('shipment_date', sa.Date(), nullable=False, comment='Дата отгрузки'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='Примечание к отгрузке'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rel_user_mark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи сборки'),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество собранных марок'),
    sa.Column('assembly_date', sa.Date(), nullable=False, comment='Дата сборки'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_user_mark')
    op.drop_table('mark_shipment')
    # ### end Alembic commands ###
