"""User Detail Marks Orders Kmd

Revision ID: 8c74db3a29b2
Revises: 
Create Date: 2026-03-12 14:05:01.979133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c74db3a29b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus').create(op.get_bind())
    # sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus').create(op.get_bind())
    # sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'ERROR', name='filestatus').create(op.get_bind())
    op.create_table('orders',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public order UUID'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_num_orders', sa.Integer(), nullable=False, comment='Внутренний номер заказа'),
    sa.Column('num_orders', sa.Integer(), nullable=False, comment='Номер заказа'),
    sa.Column('num_project', sa.String(), nullable=False, comment='Номер проекта'),
    sa.Column('internal_create_date', sa.Date(), nullable=False, comment='Дата создания самого заказа не в приложении'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False, comment='Статус заказа'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public user UUID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Unique username'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address'),
    sa.Column('hash_password', sa.String(length=255), nullable=False, comment='Hash password'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment=' Active user'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='Verified user or confirmed email'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('files',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public file UUID'),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'ERROR', name='filestatus'), nullable=False, comment='Статус файла'),
    sa.Column('order_uuid', sa.UUID(), nullable=False),
    sa.Column('hash_sum', sa.String(), nullable=False),
    sa.Column('comment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_files_hash_sum'), 'files', ['hash_sum'], unique=True)
    op.create_table('kmd',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='kdm UUID'),
    sa.Column('num_kmd', sa.String(), nullable=False, comment='Номер КМД'),
    sa.Column('order_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_kmd_num_kmd'), 'kmd', ['num_kmd'], unique=False)
    op.create_table('details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID детали (никак не связан с номером)'),
    sa.Column('num_detail', sa.String(), nullable=False, comment='Номер детали одинаковый на заказ, разный между заказами'),
    sa.Column('type', sa.String(), nullable=False, comment='Прокат, пример Лист Труба'),
    sa.Column('size', sa.String(), nullable=False, comment='Типоразмер проката'),
    sa.Column('width', sa.Float(), nullable=True, comment='Ширина иногда отсутствует'),
    sa.Column('length', sa.Float(), nullable=False, comment='Длинна всегда указана'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество деталей на марку'),
    sa.Column('steel_grade', sa.String(), nullable=False, comment='Марка стали'),
    sa.Column('operation', sa.String(), nullable=True, comment='Операции наверное могут быт пустыми'),
    sa.Column('kmd_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kmd_uuid'], ['kmd.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('kmd_uuid', 'num_detail', name='unique_kmd_detail')
    )
    op.create_index(op.f('ix_details_num_detail'), 'details', ['num_detail'], unique=False)
    op.create_index(op.f('ix_details_type'), 'details', ['type'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Айди марки'),
    sa.Column('title', sa.String(), nullable=False, comment='Название марки Б2-30'),
    sa.Column('name', sa.String(), nullable=False, comment='наименование марки Балка'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество марок на заказ'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Вес одной марки'),
    sa.Column('cooperation', sa.String(), nullable=True, comment='Кооперация'),
    sa.Column('mounting_part', sa.String(), nullable=True, comment='Признак монтажной детали'),
    sa.Column('que_num', sa.String(), nullable=True, comment='Номер очереди'),
    sa.Column('kmd_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kmd_uuid'], ['kmd.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('kmd_uuid', 'title', name='unique_kmd_mark')
    )
    op.create_table('rel_markadel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID связи'),
    sa.Column('marks_id', sa.Integer(), nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('details_quantity', sa.Integer(), nullable=False, comment='Суммарное количество деталей на все одинаковые марки'),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False, comment='Оставшееся количество деталей'),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus'), nullable=False, comment='Статус детали'),
    sa.Column('kmd_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['details.id'], ),
    sa.ForeignKeyConstraint(['kmd_uuid'], ['kmd.uuid'], ),
    sa.ForeignKeyConstraint(['marks_id'], ['marks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('marks_id', 'details_id', name='unique_mark_detail')
    )
    op.create_table('rel_userdel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID связи'),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('rel_markadel_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество сделанных деталей'),
    sa.Column('completion_date', sa.Date(), nullable=False, comment='Дата выполнения'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rel_markadel_id'], ['rel_markadel.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_userdel')
    op.drop_table('rel_markadel')
    op.drop_table('marks')
    op.drop_index(op.f('ix_details_type'), table_name='details')
    op.drop_index(op.f('ix_details_num_detail'), table_name='details')
    op.drop_table('details')
    op.drop_index(op.f('ix_kmd_num_kmd'), table_name='kmd')
    op.drop_table('kmd')
    op.drop_index(op.f('ix_files_hash_sum'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('orders')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'ERROR', name='filestatus').drop(op.get_bind())
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus').drop(op.get_bind())
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='detailsstatus').drop(op.get_bind())
    # ### end Alembic commands ###
