"""Update status kmd

Revision ID: 9e515cb360fa
Revises: 2ff3452720c6
Create Date: 2026-05-12 13:19:02.989056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e515cb360fa'
down_revision: Union[str, Sequence[str], None] = '2ff3452720c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='kmdstatus').create(op.get_bind())
    op.add_column('kmd', sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='kmdstatus', create_type=False), server_default='NEW', nullable=False, comment='Статус КМД'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kmd', 'status')
    sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='kmdstatus').drop(op.get_bind())
    # ### end Alembic commands ###
