"""update marks

Revision ID: c403ff92a307
Revises: 630e2b20e7ae
Create Date: 2026-05-21 11:31:26.352604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c403ff92a307'
down_revision: Union[str, Sequence[str], None] = '630e2b20e7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Айди марки',
               existing_nullable=False)
    op.alter_column('marks', 'name',
               existing_type=sa.VARCHAR(),
               comment='Наименование марки Балка',
               existing_comment='наименование марки Балка',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'name',
               existing_type=sa.VARCHAR(),
               comment='наименование марки Балка',
               existing_comment='Наименование марки Балка',
               existing_nullable=False)
    op.alter_column('marks', 'id',
               existing_type=sa.INTEGER(),
               comment='Айди марки',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
