"""new update quantity

Revision ID: cca6a2d75195
Revises: c403ff92a307
Create Date: 2026-06-01 23:43:29.300669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca6a2d75195'
down_revision: Union[str, Sequence[str], None] = 'c403ff92a307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_item', sa.Column('total_quantity', sa.Numeric(precision=15, scale=3), nullable=False))
    op.add_column('delivery_item', sa.Column('unit_weight', sa.Numeric(precision=10, scale=3), nullable=False))
    op.alter_column('delivery_item', 'profile_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Тип: Лист, Труба...',
               existing_nullable=False)
    op.alter_column('delivery_item', 'profile_size',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Типоразмер: 10, 25Ш1...',
               existing_nullable=False)
    op.alter_column('delivery_item', 'steel_grade',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Марка стали',
               existing_nullable=False)
    op.alter_column('delivery_item', 'total_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment=None,
               existing_comment='Общий вес в поставке, кг',
               existing_nullable=False)
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment=None,
               existing_comment='Распределено по КМД, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_item', 'allocated_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Распределено по КМД, кг',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('delivery_item', 'total_weight',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               comment='Общий вес в поставке, кг',
               existing_nullable=False)
    op.alter_column('delivery_item', 'steel_grade',
               existing_type=sa.VARCHAR(),
               comment='Марка стали',
               existing_nullable=False)
    op.alter_column('delivery_item', 'profile_size',
               existing_type=sa.VARCHAR(),
               comment='Типоразмер: 10, 25Ш1...',
               existing_nullable=False)
    op.alter_column('delivery_item', 'profile_type',
               existing_type=sa.VARCHAR(),
               comment='Тип: Лист, Труба...',
               existing_nullable=False)
    op.drop_column('delivery_item', 'unit_weight')
    op.drop_column('delivery_item', 'total_quantity')
    # ### end Alembic commands ###
