"""Update float

Revision ID: dd8f0e39de01
Revises: 25971e5c3c24
Create Date: 2026-03-27 23:18:54.779837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8f0e39de01'
down_revision: Union[str, Sequence[str], None] = '25971e5c3c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('details', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=False)
    op.alter_column('kmd', 'marks_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('marks', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=3),
               existing_comment='Вес одной марки',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'weight',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Вес одной марки',
               existing_nullable=False)
    op.alter_column('kmd', 'marks_weight',
               existing_type=sa.Numeric(precision=20, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('details', 'weight',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
