"""Update users hash_pass

Revision ID: e23a1de4680b
Revises: 4d34a58cf00c
Create Date: 2026-04-09 12:13:17.585621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23a1de4680b'
down_revision: Union[str, Sequence[str], None] = '4d34a58cf00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Hash password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Hash password')
    # ### end Alembic commands ###
