"""Update que_num

Revision ID: e6de5eddf137
Revises: e23a1de4680b
Create Date: 2026-04-09 18:37:21.508154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6de5eddf137'
down_revision: Union[str, Sequence[str], None] = 'e23a1de4680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'que_num')
    op.add_column('rel_markadel', sa.Column('que_num', sa.String(), nullable=True, comment='Номер очереди'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_markadel', 'que_num')
    op.add_column('marks', sa.Column('que_num', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Номер очереди'))
    # ### end Alembic commands ###
