"""Add weight 

Revision ID: e73a314f3d4d
Revises: 4466ef719e58
Create Date: 2026-03-12 14:18:29.657410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73a314f3d4d'
down_revision: Union[str, Sequence[str], None] = '4466ef719e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('details', 'weight')
    # ### end Alembic commands ###
